In [7]:
import numpy as np
import matplotlib.pyplot as plt

### Create numpy array of 5 Integer

In [9]:
arr=np.array([2,4,6,7,8])
arr

array([2, 4, 6, 7, 8])

In [17]:
arr_std=(arr-arr.mean())/arr.std()
arr_std

array([-1.57841037, -0.64993368,  0.27854301,  0.74278135,  1.2070197 ])

### Standard Scalar

In [15]:
from sklearn.preprocessing import StandardScaler
stdc=StandardScaler()
stdc.fit_transform(arr.reshape(-1,1))

array([[-1.57841037],
       [-0.64993368],
       [ 0.27854301],
       [ 0.74278135],
       [ 1.2070197 ]])

### Min Max Scaler

In [23]:
from sklearn.preprocessing  import MinMaxScaler

In [24]:
mmxsc=MinMaxScaler()

In [26]:
mmxsc.fit_transform(arr.reshape(-1,1))

array([[0.        ],
       [0.33333333],
       [0.66666667],
       [0.83333333],
       [1.        ]])

### Create a Dataset with 5 features

In [53]:
import pandas as pd

In [39]:
data={'name':['surya','charles','hari','selva','ebi'],
    'age':[20,21,21,22,24],
        'height':[0,180,170,167,185],
      'weight':[56,69,50,60,75],
      'bp':[100,110,90,120,102]}

In [40]:
data

{'age': [20, 21, 21, 22, 24],
 'bp': [100, 110, 90, 120, 102],
 'height': [0, 180, 170, 167, 185],
 'name': ['surya', 'charles', 'hari', 'selva', 'ebi'],
 'weight': [56, 69, 50, 60, 75]}

In [41]:
frame=pd.DataFrame(data)
frame

age   bp  height     name  weight
0   20  100       0    surya      56
1   21  110     180  charles      69
2   21   90     170     hari      50
3   22  120     167    selva      60
4   24  102     185      ebi      75

### write dataframe to file

In [42]:
frame.to_csv('record.csv',index=False)

In [43]:
df=pd.read_csv('record.csv')
df

age   bp  height     name  weight
0   20  100       0    surya      56
1   21  110     180  charles      69
2   21   90     170     hari      50
3   22  120     167    selva      60
4   24  102     185      ebi      75

### Replace all Zeros with mean of each columns

In [44]:
df=df.replace(0,df.mean())
df

age   bp  height     name  weight
0   20  100   140.4    surya      56
1   21  110   180.0  charles      69
2   21   90   170.0     hari      50
3   22  120   167.0    selva      60
4   24  102   185.0      ebi      75

### select all features expect name 

In [47]:
frame2=df[['age','bp','height','weight']]

In [48]:
frame2

age   bp  height  weight
0   20  100   140.4      56
1   21  110   180.0      69
2   21   90   170.0      50
3   22  120   167.0      60
4   24  102   185.0      75

### Apply standard scaler,minmax scaler

In [49]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [50]:
stdc=StandardScaler()
mmsc=MinMaxScaler()

In [51]:
stdc.fit_transform(frame2)

array([[-1.17953565, -0.43686581, -1.8136084 , -0.66914961],
       [-0.44232587,  0.55601103,  0.74404447,  0.78067454],
       [-0.44232587, -1.42974265,  0.09817253, -1.33829921],
       [ 0.29488391,  1.54888787, -0.09558905, -0.22304987],
       [ 1.76930347, -0.23829044,  1.06698044,  1.44982414]])

In [52]:
mmsc.fit_transform(frame2)

array([[0.        , 0.33333333, 0.        , 0.24      ],
       [0.25      , 0.66666667, 0.88789238, 0.76      ],
       [0.25      , 0.        , 0.66367713, 0.        ],
       [0.5       , 1.        , 0.59641256, 0.4       ],
       [1.        , 0.4       , 1.        , 1.        ]])