# Feature Scaling

In [1]:
import numpy as np
import pandas as pd


In [4]:
df=pd.read_csv("E:\\ML\\dataset\\feature.csv")
df.head()

id  gender  exp_years  salary
0  101    male          5    5500
1  102    male          3    3000
2  103  female          2    2100
3  104  female          5    5000
4  105    male          5    5400

## Types of features scaling
        minmax scaler
        standardize
        normalize
        binarize
        

### minmax scaler

minmaxscaler= xi-xmin/(xmax-xmin)

import sklearn library

In [5]:
from sklearn import preprocessing

In [7]:
features=df.iloc[:,[2,3]].values

In [8]:
features

array([[   5, 5500],
       [   3, 3000],
       [   2, 2100],
       [   5, 5000],
       [   5, 5400],
       [   6, 7000],
       [   7, 7300],
       [   8, 8000],
       [   2, 1500],
       [   1, 1000],
       [   1, 1000],
       [   2, 1900],
       [   3, 4000],
       [   9, 9000],
       [   8, 8100],
       [   7, 7000],
       [   7, 7100],
       [   4, 4300],
       [   4, 4000],
       [   4, 4000]], dtype=int64)

In [9]:
min_max=preprocessing.MinMaxScaler(feature_range=(0,1))

In [10]:
feature_scal=min_max.fit_transform(features)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [11]:
feature_scal

array([[0.5   , 0.5625],
       [0.25  , 0.25  ],
       [0.125 , 0.1375],
       [0.5   , 0.5   ],
       [0.5   , 0.55  ],
       [0.625 , 0.75  ],
       [0.75  , 0.7875],
       [0.875 , 0.875 ],
       [0.125 , 0.0625],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.125 , 0.1125],
       [0.25  , 0.375 ],
       [1.    , 1.    ],
       [0.875 , 0.8875],
       [0.75  , 0.75  ],
       [0.75  , 0.7625],
       [0.375 , 0.4125],
       [0.375 , 0.375 ],
       [0.375 , 0.375 ]])

## standard scaler

standard scaler= xi/std(features)

In [26]:
feature1=df.iloc[:,[2,3]].values

In [27]:
std=preprocessing.StandardScaler()

In [28]:
featstd=std.fit_transform(feature1)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [31]:
featstd

array([[ 0.1462465 ,  0.27965033],
       [-0.68944781, -0.7335755 ],
       [-1.10729496, -1.0983368 ],
       [ 0.1462465 ,  0.07700516],
       [ 0.1462465 ,  0.2391213 ],
       [ 0.56409366,  0.88758583],
       [ 0.98194082,  1.00917293],
       [ 1.39978797,  1.29287616],
       [-1.10729496, -1.341511  ],
       [-1.52514212, -1.54415617],
       [-1.52514212, -1.54415617],
       [-1.10729496, -1.17939487],
       [-0.68944781, -0.32828517],
       [ 1.81763513,  1.69816649],
       [ 1.39978797,  1.3334052 ],
       [ 0.98194082,  0.88758583],
       [ 0.98194082,  0.92811486],
       [-0.27160065, -0.20669807],
       [-0.27160065, -0.32828517],
       [-0.27160065, -0.32828517]])

## Normalize

normalizer=  xi/sqrt(sum of all the square of that row)

In [32]:
feature2=df.iloc[:,[2,3]].values

In [33]:
norm=preprocessing.Normalizer()

In [34]:
featnorm=norm.fit_transform(feature2)

In [35]:
featnorm

array([[9.09090533e-04, 9.99999587e-01],
       [9.99999500e-04, 9.99999500e-01],
       [9.52380520e-04, 9.99999546e-01],
       [9.99999500e-04, 9.99999500e-01],
       [9.25925529e-04, 9.99999571e-01],
       [8.57142542e-04, 9.99999633e-01],
       [9.58903669e-04, 9.99999540e-01],
       [9.99999500e-04, 9.99999500e-01],
       [1.33333215e-03, 9.99999111e-01],
       [9.99999500e-04, 9.99999500e-01],
       [9.99999500e-04, 9.99999500e-01],
       [1.05263100e-03, 9.99999446e-01],
       [7.49999789e-04, 9.99999719e-01],
       [9.99999500e-04, 9.99999500e-01],
       [9.87653839e-04, 9.99999512e-01],
       [9.99999500e-04, 9.99999500e-01],
       [9.85915014e-04, 9.99999514e-01],
       [9.30232156e-04, 9.99999567e-01],
       [9.99999500e-04, 9.99999500e-01],
       [9.99999500e-04, 9.99999500e-01]])

## Binarize

suppose if you give in the parameter (3) of object creation less than of equal 3 will be put zero more than 3 will be put 1

In [42]:
feature3=df.iloc[:,[2]].values

In [43]:
binarize=preprocessing.Binarizer(3)

In [44]:
featbinar=binarize.fit_transform(feature3)

In [45]:
featbinar

array([[1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=int64)